### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Newerawe** [littlstar/ls-psvr-encoder#6]
Hello. When windows version will be available? Thank you.

**Comment by tomazcdn** [comment]
I want to know too. It would Help a Lot. Today i got 3 vídeos that cant run on littlstar, its up down and i put the right name,but It didnt run and when littlstar recognize It doesnt run properly. 

But It would Help on Others cases,i use an tablet to get content,put on HDD and run on my ps4,so It would Help alot because i simples run This app and It correct the name. I simples put direct on HDD.

**Comment by Newerawe** [comment]
I use this program as a workaround
http://stormwave.uk/#downloads

**Comment by mgillespie** [comment]
If you have a recent version of Windows 10, you can install the Ubuntu subsystem under Windows, as a store app, and follow the instructions for Ubuntu.  Tried it today and it works fine.

when it's installed, do the following:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install gpac ffmpeg npm
sudo npm install littlstar/ls-psvr-encoder -g

that should do it.

**Comment by mgillespie** [comment]
Tested these instructions exact;ly as given and it worked fine.  Created a pull request to update the readme.

**Comment by alexsaesee** [comment]
Do someone test the performance of the Windows 10 WSL Ubuntu VS a real Ubuntu ?

**Comment by alexsaesee** [comment]
I think it's important to explain that we need to install the 18.04 version of Ubuntu from your link and not the proposed one in the MS Store (by default Ubuntu 16.04).
ls psvr encoder doesn't work on the Ubuntu 16.04 WSL.

I followed your post with a single command when the 18.04 installed:
`sudo apt update && sudo apt upgrade -y && sudo apt-get install gpac ffmpeg npm -y && sudo npm install littlstar/ls-psvr-encoder -g`

Now when I test `lspe -h` I have the help showing (and not an error like in the WSL Ubuntu 16.04.

Solved the Windows case for me.

**Comment by dawave23** [comment]
For anyone that's very unfamiliar with ubuntu like myself. Here is what I did to make it work. 

https://www.microsoft.com/store/productId/9N9TNGVNDL3Q

when it's installed, do the following:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install gpac
sudo apt-get install ffmpeg 
sudo apt-get install npm
sudo npm install littlstar/ls-psvr-encoder -g

I had to break the pkg into each one or it created errors when installing ls-psvr-encoder -g. 

(If you were stuck like me, feel free to RESET the ubuntu setting from Add/Remove program to start from scratch).

**Comment by Yozer** [comment]
I don't think there is any need to use linux subsystem to run ls-psvr-encoder.
I just installed:

1. ffmpeg
2. nodejs
3. mp4box
4. ls-psvr-encoder using npm

and everything works :)

![Imgur](https://i.imgur.com/tLWnhTv.png)

**Comment by Mozkau** [comment]
I'm trying to get this working on Windows 10 -> Ubuntu 18.04:

After a few install attempts i get same error:
> 
![image](https://user-images.githubusercontent.com/46965306/51611467-59faa300-1f30-11e9-89f8-dfacd5d408a5.png)

Any help would be appriciated.

**Comment by Yozer** [comment]
Your path is wrong. It should be something like:
/mnt/e/test.mp4

**Comment by Mozkau** [comment]
Should i put video to some specific directory? :S

**Comment by Bullockmush** [comment]
getting the following error

lee@DESKTOP-H8TBTOR:~$ lspe -i ~/mnt/c/1.mp4 -d 180 -t sbs
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/pos'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position/index.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
